/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import java.awt.Color;
import logic.ServerController;

/**
 *
 * @author Mare
 */
public class FrmServer extends javax.swing.JFrame {

    /**
     * Creates new form FrmServer
     */
    public FrmServer() {
        initComponents();
        
        serverStopped();
        
        setTitle("SERVER");
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnStartServer = new javax.swing.JButton();
        btnStopServer = new javax.swing.JButton();
        lblServerStatus = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jmConfiguration = new javax.swing.JMenu();
        jmiDatabase = new javax.swing.JMenuItem();
        jmiPort = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnStartServer.setText("Pokreni server");
        btnStartServer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStartServerActionPerformed(evt);
            }
        });

        btnStopServer.setText("Zaustavi server");
        btnStopServer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStopServerActionPerformed(evt);
            }
        });

        lblServerStatus.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblServerStatus.setText("jLabel1");

        jmConfiguration.setText("Konfiguracija");

        jmiDatabase.setText("Baza");
        jmiDatabase.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiDatabaseActionPerformed(evt);
            }
        });
        jmConfiguration.add(jmiDatabase);

        jmiPort.setText("Port");
        jmiPort.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiPortActionPerformed(evt);
            }
        });
        jmConfiguration.add(jmiPort);

        jMenuBar1.add(jmConfiguration);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addComponent(btnStartServer, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnStopServer, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(81, 81, 81))
            .addGroup(layout.createSequentialGroup()
                .addGap(198, 198, 198)
                .addComponent(lblServerStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(189, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addComponent(lblServerStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 69, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnStartServer)
                    .addComponent(btnStopServer))
                .addGap(65, 65, 65))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jmiDatabaseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiDatabaseActionPerformed
        new FrmDatabase(this, true).setVisible(true);
    }//GEN-LAST:event_jmiDatabaseActionPerformed

    private void jmiPortActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiPortActionPerformed
        new FrmPort(this, true).setVisible(true);
    }//GEN-LAST:event_jmiPortActionPerformed

    private void btnStartServerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStartServerActionPerformed
        serverStarted();
        
        ServerController.getInstance().startServer();
    }//GEN-LAST:event_btnStartServerActionPerformed

    private void btnStopServerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStopServerActionPerformed
        serverStopped();
        
        ServerController.getInstance().stopServer();
    }//GEN-LAST:event_btnStopServerActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnStartServer;
    private javax.swing.JButton btnStopServer;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jmConfiguration;
    private javax.swing.JMenuItem jmiDatabase;
    private javax.swing.JMenuItem jmiPort;
    private javax.swing.JLabel lblServerStatus;
    // End of variables declaration//GEN-END:variables

    private void serverStopped() {
        lblServerStatus.setText("Server nije pokrenut");
        lblServerStatus.setForeground(Color.RED);
        
        btnStartServer.setEnabled(true);
        btnStopServer.setEnabled(false);
    }

    private void serverStarted() {
        lblServerStatus.setText("Server je pokrenut");
        lblServerStatus.setForeground(Color.GREEN);
        
        btnStartServer.setEnabled(false);
        btnStopServer.setEnabled(true);
    }
}
