/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package view.student;

import domain.Student;
import javax.swing.JOptionPane;
import models.StudentTableModel;
import view.FormMode;

/**
 *
 * @author Mare
 */
public class FrmViewStudents extends javax.swing.JDialog {

    /**
     * Creates new form FrmViewStudents
     */
    public FrmViewStudents(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();

        setTitle("STUDENTI");
        setLocationRelativeTo(null);

        StudentTableModel stm = new StudentTableModel(this);

        Thread t = new Thread(stm);
        t.start();

        tblStudents.setModel(stm);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblStudents = new javax.swing.JTable();
        lblSearch = new javax.swing.JLabel();
        txtSearch = new javax.swing.JTextField();
        btnSearch = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        btniDelete = new javax.swing.JButton();
        btnDetails = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        tblStudents.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblStudents);

        lblSearch.setText("Pretraga:");

        btnSearch.setText("Pretrazi");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });

        btnUpdate.setText("Izmeni");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        btniDelete.setText("Obrisi");
        btniDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btniDeleteActionPerformed(evt);
            }
        });

        btnDetails.setText("Detalji");
        btnDetails.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDetailsActionPerformed(evt);
            }
        });

        btnCancel.setText("Otkazi");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 344, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnSearch))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 524, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnUpdate, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btniDelete, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnDetails, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnCancel, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(23, 23, 23))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(13, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSearch)
                    .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSearch))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(19, 19, 19))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnUpdate)
                        .addGap(18, 18, 18)
                        .addComponent(btniDelete)
                        .addGap(24, 24, 24)
                        .addComponent(btnDetails)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnCancel)
                        .addGap(61, 61, 61))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        String search = txtSearch.getText().trim();

        ((StudentTableModel) tblStudents.getModel()).setParametar(search);

//        JOptionPane.showMessageDialog(this, "Sistem je nasao studente po zadatoj vrenosti", "USPESNA PRETRAGA", JOptionPane.INFORMATION_MESSAGE);

    }//GEN-LAST:event_btnSearchActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        int selectedStudent = tblStudents.getSelectedRow();

        if (selectedStudent < 0) {
            JOptionPane.showMessageDialog(this, "Sistem ne moze da ucita studenta", "GRESKA PRI UCITAVANJU", JOptionPane.ERROR_MESSAGE);

            return;
        }

        Student s = ((StudentTableModel) tblStudents.getModel()).getStudent(selectedStudent);

        JOptionPane.showMessageDialog(this, "Sistem je ucitao studenta", "USPESNO UCITAVANJE", JOptionPane.INFORMATION_MESSAGE);

        new FrmStudent(this, true, FormMode.IZMENI, s).setVisible(true);
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btniDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btniDeleteActionPerformed
        int selectedStudent = tblStudents.getSelectedRow();

        if (selectedStudent < 0) {
            JOptionPane.showMessageDialog(this, "Sistem ne moze da ucita studenta", "GRESKA PRI UCITAVANJU", JOptionPane.ERROR_MESSAGE);

            return;
        }

        int response = JOptionPane.showConfirmDialog(this, "Da li ste sigurni da zelite da obrisete ovog studenta?", "BRISANJE", JOptionPane.YES_NO_OPTION);

        if (response == JOptionPane.YES_OPTION) {
            Student toDelete = ((StudentTableModel) tblStudents.getModel()).getStudent(selectedStudent);

            new FrmStudent(this, true, FormMode.OBRISI, toDelete).setVisible(true);

        } else if (response == JOptionPane.NO_OPTION) {
            return;
        }
    }//GEN-LAST:event_btniDeleteActionPerformed

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnCancelActionPerformed

    private void btnDetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDetailsActionPerformed
        int selectedStudent = tblStudents.getSelectedRow();

        if (selectedStudent < 0) {
            JOptionPane.showMessageDialog(this, "Sistem ne moze da ucita studenta", "GRESKA PRI UCITAVANJU", JOptionPane.ERROR_MESSAGE);

            return;
        }

        Student s = ((StudentTableModel) tblStudents.getModel()).getStudent(selectedStudent);

        JOptionPane.showMessageDialog(this, "Sistem je ucitao studenta", "USPESNO UCITAVANJE", JOptionPane.INFORMATION_MESSAGE);

        new FrmStudent(this, true, FormMode.PRIKAZI, s).setVisible(true);
    }//GEN-LAST:event_btnDetailsActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnDetails;
    private javax.swing.JButton btnSearch;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JButton btniDelete;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblSearch;
    private javax.swing.JTable tblStudents;
    private javax.swing.JTextField txtSearch;
    // End of variables declaration//GEN-END:variables

    void refreshTable() {
        StudentTableModel stm = (StudentTableModel) tblStudents.getModel();

        stm.refreshTable();
    }

    void deleteStudent(Student s) {
        StudentTableModel stm = (StudentTableModel) tblStudents.getModel();

        stm.refreshTable();

        stm.deleteStudent(s);
    }
}
